### ISSUE TITLE
«guo»

### ISSUE THREAD

**Issue by Ilmen-vodhr** [toaq/dictionary#65] opened 2019-07-02 12:57 UTC
```
  {
    "toaq": "guo",
    "type": "predicate",
    "english": "▯ is a repetition/instance of ▯.",
    "gloss": "instance",
    "keywords": [],
    "frame": "",
    "distribution": "d d",
    "notes": [],
    "examples": [],
    "fields": []
},
```

The serial frame and type signature of **guo** should be clarified.

**Comment by uakci** [comment] 2019-07-02 14:03
Duplicate of #16.

**Closed by uakci** 2019-07-02 14:03 UTC
Labels: frame
